package com.ajs.enums;

public enum ConfigProperties {

    URL,
    BROWSER,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPPEDSTEPSSCREENSHOTS,
    RETRYFAILEDTESTS,
    DOCKERRUN

}
